meta:
  title: hello-hooks
  author: Taka
  description: React Hooks
  thumbnail: https://avatars3.githubusercontent.com/u/7392701?s=460&v=4
  repositoryUrl: https://github.com/kashira2339/slides
  sns: ["twitter"]
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: false
  code:
    languages:
      - javascript
      - typescript
      - json
    plugins: []
extends:
  js:
  css:
